# golangci-lint configuration for Finsolvz Backend
# Compatible with golangci-lint v1.54+

run:
  timeout: 5m
  go: '1.22'
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

linters-settings:
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  gci:
    local-prefixes: finsolvz-backend
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  gocyclo:
    min-complexity: 15
  
  goimports:
    local-prefixes: finsolvz-backend
  
  govet:
    check-shadowing: true
  
  lll:
    line-length: 140
  
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - lll
        - goconst
    - path: ".*_test\\.go"
      text: "G404:" # Allow weak random number generator in tests
    - linters:
        - gosec
      text: "G404"