steps:
  # Step 1: Download dependencies
  - name: 'golang:1.23-alpine'
    entrypoint: 'go'
    args: ['mod', 'download']

  # Step 2: Run tests
  - name: 'golang:1.23-alpine'
    entrypoint: 'go'
    args: ['test', './...']

  # Step 3: Build application
  - name: 'golang:1.23-alpine'
    entrypoint: 'go'
    args: ['build', '-o', 'main', './cmd/server']
    env:
      - 'CGO_ENABLED=0'
      - 'GOOS=linux'

  # Step 4: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/finsolvz-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/finsolvz-backend:latest',
      '.'
    ]

  # Step 5: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/finsolvz-backend:$BUILD_ID']

  # Step 6: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/finsolvz-backend:latest']

  # Step 7: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'finsolvz-backend',
      '--image', 'gcr.io/$PROJECT_ID/finsolvz-backend:$BUILD_ID',
      '--region', 'asia-southeast2',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--port', '8080',
      '--set-env-vars', 'APP_ENV=production',
      '--set-secrets', 'MONGO_URI=MONGO_URI:latest,JWT_SECRET=JWT_SECRET:latest',
      '--quiet'
    ]

images:
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:latest'

timeout: '1200s'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 20