# Production CI/CD Pipeline for Finsolvz Backend
# Triggers on push to main branch
# Builds, tests, and deploys to Cloud Run automatically

steps:
  # Step 1: Run Unit Tests
  - name: 'gcr.io/cloud-builders/go'
    id: 'run-tests'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🧪 Running tests..."
        go mod download
        go test -v ./... || exit 1
        echo "✅ All tests passed"
    env:
      - 'CGO_ENABLED=0'
      - 'GOOS=linux'

  # Step 2: Build Go Binary
  - name: 'gcr.io/cloud-builders/go'
    id: 'build-binary'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🏗️ Building Go binary..."
        go mod download
        CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/server
        echo "✅ Binary built successfully"
        ls -la main
    env:
      - 'CGO_ENABLED=0'
      - 'GOOS=linux'

  # Step 3: Build and Push Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🐳 Building Docker image..."
        docker build -t gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA \
                     -t gcr.io/$PROJECT_ID/finsolvz-backend:latest .
        echo "✅ Docker image built"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "📤 Pushing Docker image..."
        docker push gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA
        docker push gcr.io/$PROJECT_ID/finsolvz-backend:latest
        echo "✅ Docker image pushed"

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-to-cloud-run'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🚀 Deploying to Cloud Run..."
        gcloud run deploy finsolvz-backend \
          --image gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --memory 1Gi \
          --cpu 1 \
          --timeout 900 \
          --max-instances 10 \
          --min-instances 0 \
          --concurrency 80 \
          --set-env-vars="APP_ENV=production,GREETING=✨ Finsolvz Production API ✨" \
          --set-secrets="MONGO_URI=MONGO_URI:latest,JWT_SECRET=JWT_SECRET:latest" \
          --quiet

        echo "✅ Deployment completed"

  # Step 5: Get Service URL
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-service-url'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🌐 Getting service URL..."
        SERVICE_URL=$(gcloud run services describe finsolvz-backend \
          --region asia-southeast2 \
          --format "value(status.url)")
        echo "Service URL: $SERVICE_URL"
        echo "$SERVICE_URL" > service_url.txt

  # Step 6: Health Check
  - name: 'gcr.io/cloud-builders/curl'
    id: 'health-check'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🏥 Running health check..."
        SERVICE_URL=$(cat service_url.txt)
        
        # Wait for service to be ready
        for i in {1..30}; do
          if curl -f --max-time 10 "$SERVICE_URL/" > /dev/null 2>&1; then
            echo "✅ Health check passed"
            exit 0
          fi
          echo "⏳ Waiting for service to be ready... ($i/30)"
          sleep 10
        done
        
        echo "❌ Health check failed after 5 minutes"
        exit 1

  # Step 7: API Test
  - name: 'gcr.io/cloud-builders/curl'
    id: 'api-test'
    entrypoint: 'sh'  
    args:
      - '-c'
      - |
        echo "🧪 Testing API endpoints..."
        SERVICE_URL=$(cat service_url.txt)
        
        # Test login endpoint
        echo "Testing login..."
        LOGIN_RESPONSE=$(curl -s -X POST "$SERVICE_URL/api/login" \
          -H "Content-Type: application/json" \
          -d '{"email":"admin@finsolvz.com","password":"admin123"}')
        
        if echo "$LOGIN_RESPONSE" | grep -q "access_token"; then
          echo "✅ Login endpoint working"
        else
          echo "❌ Login endpoint failed"
          echo "Response: $LOGIN_RESPONSE"
          exit 1
        fi
        
        # Test health endpoint
        HEALTH_RESPONSE=$(curl -s "$SERVICE_URL/")
        if echo "$HEALTH_RESPONSE" | grep -q "healthy"; then
          echo "✅ Health endpoint working"
        else
          echo "❌ Health endpoint failed"
          exit 1
        fi
        
        echo "✅ All API tests passed"

  # Step 8: Slack Notification (Optional)
  - name: 'gcr.io/cloud-builders/curl'
    id: 'notify-success'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "📢 Sending success notification..."
        SERVICE_URL=$(cat service_url.txt)
        
        # You can add Slack webhook here if needed
        # curl -X POST -H 'Content-type: application/json' \
        #   --data "{\"text\":\"✅ Finsolvz Backend deployed successfully!\nURL: $SERVICE_URL\"}" \
        #   $SLACK_WEBHOOK_URL
        
        echo "🎉 Deployment pipeline completed successfully!"
        echo "Service URL: $SERVICE_URL"

# Images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:latest'

# Build configuration
options:
  # Use faster machine type for builds
  machineType: 'E2_HIGHCPU_8'
  # Set build timeout (20 minutes)
  timeout: '1200s'
  # Increase disk size for Docker builds
  diskSizeGb: 20
  # Use substitution for better flexibility
  substitution_option: 'ALLOW_LOOSE'

# Build triggers will use these substitutions
substitutions:
  _SERVICE_NAME: 'finsolvz-backend'
  _REGION: 'asia-southeast2'
  _MEMORY: '1Gi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'

# Logging configuration
logsBucket: 'gs://${PROJECT_ID}-build-logs'