# Cloud Build with Custom Logs Bucket
steps:
  # Build steps
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'go'
    args: ['mod', 'download']
    
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'go'
    args: ['test', './...']
    
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'go'
    args: ['build', '-o', 'main', './cmd/server']
    env: ['CGO_ENABLED=0', 'GOOS=linux']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'finsolvz-backend',
      '--image', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA',
      '--region', 'asia-southeast2',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-secrets', 'MONGO_URI=MONGO_URI:latest,JWT_SECRET=JWT_SECRET:latest',
      '--quiet'
    ]

images:
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA'

timeout: '1200s'

# Use custom logs bucket
logsBucket: 'gs://finsolvz-backend-dev-build-logs'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 20
  substitutionOption: 'ALLOW_LOOSE'
