# Simplified Cloud Build for Testing
steps:
  # Step 1: Test Go build
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'go'
    args: ['mod', 'download']
    
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'go'
    args: ['build', './cmd/server']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA',
      '.'
    ]

  # Step 3: Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA'
    ]

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'finsolvz-backend',
      '--image', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA',
      '--region', 'asia-southeast2',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-secrets', 'MONGO_URI=MONGO_URI:latest,JWT_SECRET=JWT_SECRET:latest'
    ]

# Root level timeout (20 minutes)
timeout: '1200s'

# Simple options
options:
  machineType: 'E2_HIGHCPU_8'

# Images to store
images:
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA'