# Minimal Cloud Build Configuration - No Logging Issues
# This should work without any bucket or service account issues

steps:
  # Step 1: Download dependencies
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'go'
    args: ['mod', 'download']

  # Step 2: Run tests
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'go'
    args: ['test', './...']

  # Step 3: Build application
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'go'
    args: ['build', '-o', 'main', './cmd/server']
    env:
      - 'CGO_ENABLED=0'
      - 'GOOS=linux'

  # Step 4: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/finsolvz-backend:latest',
      '.'
    ]

  # Step 5: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA'
    ]

  # Step 6: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'finsolvz-backend',
      '--image', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA',
      '--region', 'asia-southeast2',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--port', '8787',
      '--set-env-vars', 'APP_ENV=production,PORT=8787',
      '--set-secrets', 'MONGO_URI=MONGO_URI:latest,JWT_SECRET=JWT_SECRET:latest',
      '--quiet'
    ]

# Store built images
images:
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:latest'

# Build timeout
timeout: '1200s'