# Updated Cloud Build for production
steps:
  # 1. Run Tests
  - name: 'gcr.io/cloud-builders/go'
    id: 'Run Tests'
    args: ['test', './...']
    env: ['CGO_ENABLED=0']

  # 2. Build Application
  - name: 'gcr.io/cloud-builders/go'
    id: 'Build Application'
    args: ['build', '-o', 'main', './cmd/server']
    env: ['CGO_ENABLED=0']

  # 3. Build and Push Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args: ['push', 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA']

  # 4. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      - 'run'
      - 'deploy'
      - 'finsolvz-backend'
      - '--image=gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA'
      - '--region=asia-southeast2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8787'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=APP_ENV=production,PORT=8787,GREETING=✨ Finsolvz Production API ✨'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest,MONGO_URI=MONGO_URI:latest,NODEMAILER_EMAIL=NODEMAILER_EMAIL:latest,NODEMAILER_PASS=NODEMAILER_PASS:latest'

images:
  - 'gcr.io/$PROJECT_ID/finsolvz-backend:$COMMIT_SHA'

# Configure secrets in Cloud Build Trigger UI:
# JWT_SECRET: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
# MONGO_URI: projects/$PROJECT_ID/secrets/MONGO_URI/versions/latest
# NODEMAILER_EMAIL: projects/$PROJECT_ID/secrets/NODEMAILER_EMAIL/versions/latest
# NODEMAILER_PASS: projects/$PROJECT_ID/secrets/NODEMAILER_PASS/versions/latest