name: Production Health Check

on:
  schedule:
    # Run health check every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Health and performance check
      run: |
        SERVICE_URL="https://finsolvz-backend-asia-southeast2-${{ secrets.GCP_PROJECT_ID }}.a.run.app"
        
        # Health check
        response=$(curl -s -o /dev/null -w "%{http_code}" $SERVICE_URL)
        if [ "$response" != "200" ]; then
          echo "❌ Health check failed - Status: $response"
          exit 1
        fi
        
        # Performance check
        start_time=$(date +%s%N)
        curl -s $SERVICE_URL > /dev/null
        end_time=$(date +%s%N)
        duration=$(( (end_time - start_time) / 1000000 ))
        
        if [ $duration -gt 3000 ]; then
          echo "⚠️ Slow response: ${duration}ms"
          exit 1
        fi
        
        echo "✅ Health OK (${duration}ms)"